# Generated by Django 5.1 on 2024-09-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='rol',
            field=models.CharField(choices=[('Administrador del departamento', 'Administrador del departamento'), ('Tutor', 'Tutor'), ('Asistente', 'Asistente')], default='Tutor', max_length=50),
        ),
    ]
