# Generated by Django 5.1 on 2024-10-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_roles_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='tamaño',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archivos',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
