# Generated by Django 5.1 on 2024-09-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_comentario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='correo',
            field=models.EmailField(max_length=500),
        ),
    ]
