# Generated by Django 5.1 on 2024-09-22 14:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_comentario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='No especificada', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.CharField(blank=True, default='0000000000', max_length=14, validators=[django.core.validators.RegexValidator(message='El número de teléfono solo puede contener hasta 14 dígitos.', regex='^\\d{1,14}$')]),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
